#! /bin/sh

IMAGEDIR="docs/images"
CURRENTTIME=`date +%s`
IMAGEFILENAME="ss-${CURRENTTIME}.png"
TARGET="${IMAGEDIR}/${IMAGEFILENAME}"
IMAGETAG="![screenshot](${TARGET})"

mkdir -p ${IMAGEDIR}

screencapture -i "${TARGET}"

echo "${IMAGETAG}"

IMAGEOPTIM="open -a ImageOptim"
`${IMAGEOPTIM} ${TARGET}`
